version: '3.6'

services: 
    db:
        build: .
        container_name: mysql_laptop_repair
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
        ports: 
            - 3307:3306
